# https://ionic.io/ionicons
# <ion-icon name="[[name]]"></ion-icon>
# name = "https://example.com/"




logo-linkedin = "https://www.linkedin.com/in/pyae-phyo-zaw-989482156/"
logo-github = "https://github.com/PyaeZaw97"

